;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-brace
        c-electric-colon
        c-electric-paren
        c-electric-pound
        c-electric-semi&comma
        c-electric-slash
        c-electric-star
        c-indent-line-or-region
        indent-for-tab-command
        php-expand-abbrev
        sgml-maybe-name-self
        sgml-slash
        sp--self-insert-command
        ))

(setq mc/cmds-to-run-once
      '(
        python-indent-dedent-line-backspace
        upcase-region
        ))
