;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-semi&comma
        c-electric-slash
        indent-for-tab-command
        php-expand-abbrev
        sgml-slash
        ))

(setq mc/cmds-to-run-once
      '(
        python-indent-dedent-line-backspace
        upcase-region
        ))
